alias cac='conda activate'
alias cel='conda env list'
alias cde='conda deactivate'
alias wpy='which python'
alias doihave='pip list | grep'
alias newproject='cookiecutter https://gitlab.com/epfl-center-for-imaging/image-analysis-template-project.git'