# Book settings
title: The Image Analysis Field Guide
author: EPFL Center for Imaging
logo: "icon.png"
copyright: "2024"
# Also build notebooks that are not explicitely referenced in the table of contents:
only_build_toc_files: false

launch_buttons:
  notebook_interface : jupyterlab
  jupyterhub_url: "http://frank3:8000/"  # The URL for your JupyterHub (e.g. http://localhost:8000/)

execute:
  # execute_notebooks: "cache"
  # execute_notebooks: "off"
  execute_notebooks: "auto"
  # Do not exectute the computational notebooks; only the itables
  exclude_patterns:
    - '*.ipynb'

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/EPFL-Center-for-Imaging/image-analysis-field-guide/
  branch: main
  path_to_book: "src"

html:
  announcement: "<img src='https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People%20with%20professions/Construction%20Worker%20Medium%20Skin%20Tone.png' width='25' height='25' /> This site is a prototype! Please give us your feedback by filling in our <a href='https://forms.gle/toHAP2ydydXBCndGA'>survey form</a>. Thank you!"
  favicon: "logo.ico"
  use_issues_button: false
  use_repository_button: true
  comments:
    hypothesis: false

sphinx:
  extra_extensions:
    - nbsphinx
    - sphinx_gallery.load_style
  config:
    html_show_copyright: false
    nbsphinx_thumbnails:
      "sections/python_setup": "_images/epfl.jpeg"
      "sections/notebooks/tutorials/registration_3D_analysis": "_images/alert-geo.jpeg"
      "sections/notebooks/tutorials/tracking_intro": "_images/tracking_fig.jpeg"
      "sections/notebooks/tutorials/denoising_intro": "_images/denoising_lg.jpeg"
      "sections/notebooks/tutorials/image_manipulation": "_images/epfl.jpeg"
      "sections/notebooks/tutorials/registration_intro": "_images/dic_fig.jpeg"
      "sections/notebooks/tutorials/segmentation_intro": "_images/segmentation_lg.jpeg"
      "sections/notebooks/tutorials/performance_dask_image": "_images/dask_image_lg.jpeg"
      "sections/notebooks/tutorials/segmentation_stardist": "_images/stardist_fig.jpeg"
      "sections/notebooks/tutorials/visualization_napari": "_images/segmentation_fig.jpeg"
      "sections/epfl_case_studies/crystallites_annotation": "_images/triangles_fig.jpeg"
      "sections/epfl_case_studies/lungs_segmentation_ct": "_images/lungs_fig.jpeg"
      "sections/epfl_case_studies/skeletonization": "_images/drosofig.jpeg"

parse:
  myst_enable_extensions:
    - linkify
    - html_admonition
    - dollarmath