# Book settings
title: The Image Analysis Field Guide
author: EPFL Center for Imaging
logo: "icon.png"
copyright: "2024"
# Also build notebooks that are not explicitely referenced in the table of contents:
only_build_toc_files: false

launch_buttons:
  notebook_interface : jupyterlab
  jupyterhub_url: "http://localhost:8000/"
  # jupyterhub_url: "http://frank1:8000/"

execute:
  # execute_notebooks: "cache"
  # execute_notebooks: "off"  
  execute_notebooks: "auto"
  # Do not exectute the computational notebooks; only the itables
  # exclude_patterns:
  #   - '*.ipynb'

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/EPFL-Center-for-Imaging/image-analysis-field-guide/
  branch: main
  path_to_book: "src"

html:
  announcement: "<img src='https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People%20with%20professions/Construction%20Worker%20Medium%20Skin%20Tone.png' width='25' height='25' /> This site is a prototype! Please <a href='https://forms.gle/toHAP2ydydXBCndGA' style='color: orange;'>give us your feedback</a>. Thank you!"
  favicon: "logo.ico"
  use_issues_button: false
  use_repository_button: true
  comments:
    hypothesis: false

sphinx:
  extra_extensions:
    - nbsphinx
    - sphinx_gallery.load_style
  config:
    html_show_copyright: false
    nbsphinx_thumbnails:
      ## Temporary - until we find a way to display a cell output with nbsphinx
      "sections/python/notebooks/python_setup": "_images/epfl.jpeg"
      "sections/python/notebooks/python_image_manipulation": "_images/epfl.jpeg"
      "sections/image_registration/notebooks/registration_intro": "_images/epfl.jpeg"
      "sections/detection_and_tracking/notebooks/tracking_intro": "_images/epfl.jpeg"
      "sections/image_denoising/notebooks/denoising_intro": "_images/epfl.jpeg"
      "sections/performance_optimization/notebooks/performance_dask_image": "_images/epfl.jpeg"
      "sections/performance_optimization/notebooks/performance_cucim": "_images/epfl.jpeg"
      "sections/image_segmentation/notebooks/segmentation_intro": "_images/epfl.jpeg"
      "sections/image_segmentation/notebooks/segmentation_stardist": "_images/epfl.jpeg"
      "sections/image_data_visualization/notebooks/visualization_napari": "_images/epfl.jpeg"
      "sections/image_data_visualization/notebooks/visualization_zarr": "_images/epfl.jpeg"
      "sections/image_reconstruction/notebooks/reconstruction_deblur": "_images/epfl.jpeg"
      "sections/fiji/notebooks/fiji_intro": "_images/epfl.jpeg"

parse:
  myst_enable_extensions:
    - linkify
    - html_admonition
    - dollarmath