# Book settings
title: The Image Analysis Field Guide
author: EPFL Center for Imaging
logo: "icon.png"
copyright: "2024"
# Also build notebooks that are not explicitely referenced in the table of contents:
only_build_toc_files: false

launch_buttons:
  notebook_interface : jupyterlab
  jupyterhub_url: "http://localhost:8000/"  # The URL for your JupyterHub.

execute:
  # execute_notebooks: "cache"
  # execute_notebooks: "off"
  execute_notebooks: "auto"
  # Do not exectute the computational notebooks; only the itables
  exclude_patterns:
    - '*.ipynb'

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/EPFL-Center-for-Imaging/image-analysis-field-guide/
  branch: main
  path_to_book: "src"

html:
  announcement: "<img src='https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People%20with%20professions/Construction%20Worker%20Medium%20Skin%20Tone.png' width='25' height='25' /> This site is a prototype! Please give us your feedback by filling in our <a href='https://docs.google.com/forms/d/e/1FAIpQLScl3ho-P_F_vO-wSG1CLJCkxEipImF0cQuY_l_o12CRWbKp0Q/viewform?usp=sf_link'>survey form</a>. Thank you!"
  favicon: "logo.ico"
  use_issues_button: false
  use_repository_button: true
  comments:
    hypothesis: true

sphinx:
  config:
    html_show_copyright: false
  
parse:
  myst_enable_extensions:
    - linkify
    - html_admonition